name: On Challenge review-completed commented

on:
  issue_comment

jobs:
  check-label-aswasignoff: 
    # if: contains(github.event.pull_request.labels.*.name, 'review-completed')
    # if : ${{ github.event.issue.label.name == 'review-completed' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check for command type
      id: command
      uses: xt0rted/slash-command-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        command: aswasignoff
        reaction: "true"
        reaction-type: "hooray"
        allow-edits: "false"
        permission-level: admin
    - name: 'Act on command aswasignoff'
      uses: actions/github-script@v3
      if: |
        steps.command.outputs.aswasignoff
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
           
    - name: Run
      run: |
        echo "The command was '${{ steps.command.outputs.aswasignoff }}' on PR #${{ github.event.issue.number }} by @${{ github.event.issue_comment.user.login }}"
      # const request = {
      #   owner: context.repo.owner,
      #   repo: context.repo.repo,
      #   pull_number: context.issue.number
      # }
      # core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
      # try {
      #   const result = await github.pulls.get(request)
      #   return result.data
      # } catch (err) {
      #   core.setFailed(`Request failed with error ${err}`)
      # }
  
  check-label-ghasignoff:
    if : ${{ github.event.issue.label.name == 'review-completed' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check for command type
      id: command
      uses: xt0rted/slash-command-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        command: ghasignoff
        reaction: "true"
        reaction-type: "+1"
        allow-edits: "false"
        permission-level: admin
    - name: Act on command ghasignoff
      uses: actions/github-script@v3
      if: |
        steps.command.outputs.ghasignoff
    - name: Run
      run: |
        echo "The command was '${{ steps.command.outputs.ghasignoff }}' on PR #${{ github.event.issue.number }} by @${{ github.event.issue_comment.user.login }}"
  check-label-socialsignoff:
    if : ${{ github.event.issue.label.name == 'review-completed' }}
    runs-on: ubuntu-latest  
    steps:
    - name: Check for command type
      id: command
      uses: xt0rted/slash-command-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        command: socialsignoff
        reaction: "true"
        reaction-type: "heart"
        allow-edits: "false"
        permission-level: admin
    - name: Act on command socialsignoff
      uses: actions/github-script@v3
      if: |
        steps.command.outputs.socialsignoff
    - name: Run
      run: |
        echo "The command was '${{ steps.command.outputs.socialsignoff }}' on PR #${{ github.event.issue.number }}"
  check-label-reposignoff:
    if : ${{ github.event.issue.label.name == 'review-completed' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check for command type
      id: command
      uses: xt0rted/slash-command-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        command: reposignoff
        reaction: "true"
        reaction-type: "eyes"
        allow-edits: "false"
        permission-level: admin
    - name: Act on command reposignoff
      uses: actions/github-script@v3
      if: |
        steps.command.outputs.reposignoff
    - name: Run
      run: |
        echo "The command was '${{ steps.command.outputs.reposignoff }}' on PR #${{ github.event.issue.number }}"
  check-label-retrosignoff:
    if : ${{ github.event.issue.label.name == 'review-completed' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check for command type
      uses: xt0rted/slash-command-action@v1
      id: command
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        command: retrosignoff
        reaction: "true"
        reaction-type: "rocket"
        allow-edits: "false"
        permission-level: admin
    - name: Act on command retrosignoff
      uses: actions/github-script@v3
      if: |
        steps.command.outputs.retrosignoff
    - name: Run
      run: |
        echo "The command was '${{ steps.command.outputs.retrosignoff }}' on PR #${{ github.event.issue.number }}"